### Register
POST http://localhost:8000/auth/register
Content-Type: application/json

{
    "email": "fastapi2@jannsen.org",
    "password": "paSSw0rd",
    "permissions": ["fastapi:users:read", "fastapi:users:write"]
}

### GET request to example server
POST http://localhost:8000/auth/login
Content-Type: application/x-www-form-urlencoded

username = fastapi2@jannsen.org &
password = password


### users/me
GET http://localhost:8000/users/me
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NjNkMDBlZWY0NWQ0Yjg3MmMxYTZhYTAiLCJhdWQiOlsiZmFzdGFwaS11c2VyczphdXRoIl0sImV4cCI6MTcxNTI3NzY1N30.1DZtIwjm0QRk8_4-wCILL1zPqjA2ZwSeemOmSKyhb-Q
Content-Type: application/json


### users/<id>
GET http://localhost:8000/users/6639412f3135a0f0b7de9541
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NjM5NDEyZjMxMzVhMGYwYjdkZTk1NDEiLCJhdWQiOlsiZmFzdGFwaS11c2VyczphdXRoIl0sImV4cCI6MTcxNTAzMzUzMn0.6tmNaagE_VA3jP2kZ_qw7FXo4br3tEb_Fyt5x7bFGDc
Content-Type: application/json


### authenticated-route
GET http://localhost:8000/authenticated-route
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NjM5NmY1NjcxY2EyYzUzOTZmNzdkYmYiLCJhdWQiOlsiZmFzdGFwaS11c2VyczphdXRoIl0sImV4cCI6MTcxNTA0NDI1MX0.xvUZAmKpRssFEe5-pa8Ew0ZsO8iKEOQKEZMRD1Syn0A
Content-Type: application/json


### request-verify-token
POST http://localhost:8000/auth/request-verify-token
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NjM5NmY1NjcxY2EyYzUzOTZmNzdkYmYiLCJhdWQiOlsiZmFzdGFwaS11c2VyczphdXRoIl0sImV4cCI6MTcxNTA0NDI1MX0.xvUZAmKpRssFEe5-pa8Ew0ZsO8iKEOQKEZMRD1Syn0A
Content-Type: application/json

{
  "email": "test@test.com"
}

### verify-token
POST http://localhost:8000/auth/verify
Content-Type: application/json

{
  "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NjM5ZDBjMGE3NzYwMDEyNmIxMGRiYjYiLCJlbWFpbCI6ImZhc3RhcGlAamFubnNlbi5vcmciLCJhdWQiOiJmYXN0YXBpLXVzZXJzOnZlcmlmeSIsImV4cCI6MTcxNTA2ODYyNH0.cAwvR9MB5MD0efvPuFchKdoFDrCsJ6AfXIZDB1Lyuuw"
}