### Register
POST http://localhost:8000/auth/register
Content-Type: application/json

{
    "email": "test_register_1@example.org",
    "password": "paSSw0rd",
    "permissions": ["fastapi:users:read", "fastapi:users:write"]
}

### GET request to example server
POST http://localhost:8000/auth/login
Content-Type: application/x-www-form-urlencoded

username = test_register_1@example.org &
password = paSSw0rd


### users/me
GET http://localhost:8000/users/me
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI1M2M0MWIzNi1hZGE3LTRlMTctYmY0Yy03MDg2MGQ2MDdmYmEiLCJhdWQiOlsiZmFzdGFwaS11c2VyczphdXRoIl0sImV4cCI6MTcxNjEzNDg4NH0.xaT6DxrQwtjKShMVsPK7DbaUBYqXnl3YgFYFq97mdgk
Content-Type: application/json


### users/<id>
GET http://localhost:8000/users/9b05ac09-123e-45a8-8394-2d277a398dd5
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI5YjA1YWMwOS0xMjNlLTQ1YTgtODM5NC0yZDI3N2EzOThkZDUiLCJhdWQiOlsiZmFzdGFwaS11c2VyczphdXRoIl0sImV4cCI6MTcxNjEzMzY4OH0.G-s3FE57QUpJPs2lhyB7Ws4zeCunAU7_OEqDp2cKfe0
Content-Type: application/json


### authenticated-route
GET http://localhost:8000/authenticated-route
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI5YjA1YWMwOS0xMjNlLTQ1YTgtODM5NC0yZDI3N2EzOThkZDUiLCJhdWQiOlsiZmFzdGFwaS11c2VyczphdXRoIl0sImV4cCI6MTcxNjEzNDA0NX0.wtuLpKzun0GrnbXqKA-PnD8DHfCeiWBM4SURCVaxZdA
Content-Type: application/json


### request-verify-token
POST http://localhost:8000/auth/request-verify-token
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NjM5NmY1NjcxY2EyYzUzOTZmNzdkYmYiLCJhdWQiOlsiZmFzdGFwaS11c2VyczphdXRoIl0sImV4cCI6MTcxNTA0NDI1MX0.xvUZAmKpRssFEe5-pa8Ew0ZsO8iKEOQKEZMRD1Syn0A
Content-Type: application/json

{
  "email": "test@test.com"
}

### verify-token
POST http://localhost:8000/auth/verify
Content-Type: application/json

{
  "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NjM5ZDBjMGE3NzYwMDEyNmIxMGRiYjYiLCJlbWFpbCI6ImZhc3RhcGlAamFubnNlbi5vcmciLCJhdWQiOiJmYXN0YXBpLXVzZXJzOnZlcmlmeSIsImV4cCI6MTcxNTA2ODYyNH0.cAwvR9MB5MD0efvPuFchKdoFDrCsJ6AfXIZDB1Lyuuw"
}